# Generated by Django 5.1.6 on 2025-04-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_historicalcontact_historicalcontactaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactaddress',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='contactaddress',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='historicalcontactaddress',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='historicalcontactaddress',
            name='street_name',
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='street',
            field=models.CharField(default='', help_text='building number and street name', max_length=150, verbose_name='street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontactaddress',
            name='street',
            field=models.CharField(default='', help_text='building number and street name', max_length=150, verbose_name='street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='unit_type',
            field=models.CharField(default='unit', help_text='P.O. Box, Unit, Suite, etc.', max_length=20, verbose_name='unit type'),
        ),
        migrations.AlterField(
            model_name='historicalcontactaddress',
            name='unit_type',
            field=models.CharField(default='unit', help_text='P.O. Box, Unit, Suite, etc.', max_length=20, verbose_name='unit type'),
        ),
    ]
